### ISSUE TITLE
testnet address validation

### ISSUE THREAD

**Issue by snogcel** [darkcoin/darkcoin#101]
I was going to clear out my old testnet wallet so I can get a fresh set of denoms going, but seems that TestNet addresses aren't validating. See screenshots below:

from Qt: http://screencast.com/t/PcLqal7Zt
from Console: http://screencast.com/t/WSHJhJHMwlT

was attempting to send to: mmfb6hxTdLT3gQGAEDr2g6Qug8ew2MwKoJ

Edit: Running 64 bit version of wallet on Windows 10

**Comment by vertoe** [comment]
testnet address version changed. 

- Changed testnet address versions to start with x or y (instead of m or n, this affects public keys only, old wallets remain valid and usable!)
