### ISSUE TITLE
Wrong value of "coinbasevalue" in getblocktemplate

### ISSUE THREAD

**Issue by Coinotron** [darkcoin/darkcoin#119]
Getblocktemplate output issue.

Version 11 doesn't include payee_amount in coinbasevalue while version 10 did that.

It is quite urgent because Stratum pool software is prepared for ver 10 like output.

**Comment by darkcoinproject** [comment]
The darkcoin network is currently in a compatibility mode, which supports both v10/v11. I would downgrade while we work out these issues, sorry for the inconvenience.

**Comment by darkcoinproject** [comment]
Which version are you using? I've looked at 11.0.7 and getblocktemplate does have payee_amount:


10:47:11
￼
getblocktemplate


10:47:11
￼
{
"version" : 2,
"previousblockhash" : "00000000000251428a5d1dd6f857dc34b706a8801039c4f969c1ae85ba5ebede",
"transactions" : [
],
"coinbaseaux" : {
"flags" : "062f503253482f"
},
"coinbasevalue" : 325000000,
"target" : "000000000011ad63000000000000000000000000000000000000000000000000",
"mintime" : 1421602678,
"mutable" : [
"time",
"transactions",
"prevblock"
],
"noncerange" : "00000000ffffffff",
"sigoplimit" : 20000,
"sizelimit" : 1000000,
"curtime" : 1421603231,
"bits" : "1b11ad63",
"height" : 205305,
"votes" : [
],
"payee" : "XrTWWGEvzg6ZkjFui1kp242kEdcmLB6MVs",
"payee_amount" : 175000000,
"masternode_payments" : true,
"enforce_masternode_payments" : true
}

**Comment by Coinotron** [comment]
I'm using 11.0.7
The problem is that in ver. 11.0.7  "coinbasevalue" is : 325000000 while in ver. 10.x.x it is 500000000 !
The issue is caused by different implementation of getblocktemplate in rpcmining.cpp in those versions:

ver 10:
result.push_back(Pair("coinbasevalue", (int64_t)pblock->vtx[0].GetValueOut()));

ver 11: 
result.push_back(Pair("coinbasevalue", (int64_t)pblock->vtx[0].vout[0].nValue));

**Comment by darkcoinproject** [comment]
Ah, yes you're correct. It's fixed in 6dd7e0f1ce2ff7b810e9d3d53211697212065c3e

**Comment by Coinotron** [comment]
Thanks
