### ISSUE TITLE
EXCEPTION: St12out_of_range   

### ISSUE THREAD

**Issue by buechling** [darkcoin/darkcoin#173]
I could not find any information on this, so i will report it here..

error was active for about 10 hours, restarting darkcoind did help. but then error comes again..

	{
		"version" : 110014,
		"protocolversion" : 70054,
		"walletversion" : 61000,
		"balance" : 8.00198744,
		"darksend_balance" : 0.00000000,
		"blocks" : 218002,
		"timeoffset" : 1,
		"connections" : 29,
		"proxy" : "",
		"difficulty" : 5928.49172684,
		"testnet" : false,
		"keypoololdest" : 1422800938,
		"keypoolsize" : 1001,
		"paytxfee" : 0.00000000,
		"relayfee" : 0.00001000,
		"errors" : "EXCEPTION: St12out_of_range       \nCInv::GetCommand() : type=7 unknown type       \ndarkcoin in ProcessMessages()       \n"
	}

**Comment by evan82** [comment]
You just need to update: https://www.darkcoin.io/downloads/

There's a few new kinds of messages supported by the client

**Comment by buechling** [comment]
yes, seems better now..

but it's not really user-friendly to make people updating every week..

	{
    "version" : 110119,
    "protocolversion" : 70066,
    "walletversion" : 61000,
    "balance" : 0.00068744,
    "darksend_balance" : 0.00000000,
    "blocks" : 218016,
    "timeoffset" : 2,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 3880.46429304,
    "testnet" : false,
    "keypoololdest" : 1422800938,
    "keypoolsize" : 1001,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00001000,
    "errors" : ""
	}
