### ISSUE TITLE
remove bitcoin exception from dash blockchain nHeight checks

### ISSUE THREAD

**Issue by camenlx** [darkcoin/darkcoin#2156]
https://github.com/dashpay/dash/blob/e596762ca22d703a79c6880a9d3edb1c7c972fd3/src/validation.cpp#L2018..#L2020

**Comment by UdjinM6** [comment]
Same logic as in #2163

**Comment by camenlx** [comment]
My comment to clean dead code is not only because it is ugly useless code, any 'executing' dead code do cause dead weight/delay to execute it. Compare cpu clocks of dead code to number times this function is called and executed by all nodes.
I could argue I did found some other useless refactoring to increase only code beauty and readability but actually did increase the diff with upstream code. Thanks for reply.
