### ISSUE TITLE
mncache.dat has problem with Enable Hot/Cold Masternode status.

### ISSUE THREAD

**Issue by thelazier** [darkcoin/darkcoin#294]
For v.11.2.16, I just found that Hot/Cold Masternode setup has problem against implementation of mncache.dat
After restart dashd , mn list read from mncache without checking to enable Hot/Cold Masternode. So, the Masternode status is invalid on daemon. Then, trying to send start from wallet will be ignore by daemon since the MN is already in the list. 

So, to make remote enable again, I remove mncache.dat and restart , the daemon can get its own MN from dsee and can re-enable masternode remotely success.

My current workaround, just create an invalid mncache.dat and ignore error about mncache.dat then my dashd is working and restarting with no problem :)

**Comment by UdjinM6** [comment]
https://github.com/darkcoin/darkcoin/pull/290

**Comment by thelazier** [comment]
closed as fixed. :)
