### ISSUE TITLE
Automatic updates of DarkCoin-Wallet software

### ISSUE THREAD

**Issue by SecUpwN** [darkcoin/darkcoin#6]
Hey @darkcoinproject, would it be possible for you to add automatic updates of the DarkCoin-Wallet software? I would like to always be on the bleeding edge without having to visit your website each time to grab the latest `darkcoin-qt` binary. Thank you so much for developing this, works great on openSUSE!

**Comment by vertoe** [comment]
Not a darkcoin issue, can be closed.
